### ISSUE TITLE
Multisite: Remaining space is not recalculated. Simple solution: Remove transient

### ISSUE THREAD

**Issue by praul** [giuliopanda/op-bulk-image-resizer#1]
Hi there and thanks for this plugin - it really does what it should do. Clients do upload biiig images, and this is perfect.
I'm utilizing this on a multisite. When I bulk resize existing images, the quota of the respective subsite does not get refreshed.
It took me a while, but the solution is simple. When bulk resizing is done, the plugin should delete the 'dirsize_cache' transient.

`delete_transient('dirsize_cache')`

It would be great if you could implement this, so I don't have to create a solution myself.
Thanks a lot

**Comment by giuliopanda** [comment]
Hi, thanks for the report. I am not very familiar with multiple wordpress sites, this morning I tried to install a local version, but I did not understand when the transient is set. Anyway I thought I'd make this change if you can help me test it, would you help me.

Inside the file /includes/class-bulk-image-resizer-loader-ajax.php line
131 I would add:

$upload_dir = wp_get_upload_dir();
clean_dirsize_cache ($upload_dir["basedir"]);

In theory, this does not delete all the transient, but only the upload part. Testing it didn't give me an error locally, if you think it's okay, I'll add it and update the plugin.

**Comment by praul** [comment]
I tested it, but it seems this action does not trigger a complete recalculation of space used. 
`delete_transient('dirsize_cache');`
on the same line works though. Should be safe, I think. After all - it's just a transient.

This is how wordpress displays used space on multisites:
![image](https://user-images.githubusercontent.com/38807639/189114244-70939f57-a8c6-4bd6-a119-aa9354afe7ad.png)

It's strange though, the documentation to clean_dirsize_cache suggests, this would work as well.

**Comment by giuliopanda** [comment]
Thanks for the test. I updated the plugin with the line of code (delete_transient ('dirsize_cache');) you suggested. If there are any problems let me know.

If you want to spend two minutes to rate it on wordpress I'm glad: D
