### ISSUE TITLE
Restoring or Undoing the resizes

### ISSUE THREAD

**Issue by GabrielSerealia** [giuliopanda/op-bulk-image-resizer#2]
If we didn't delete the original images via the setting. How do you restore them? Do you just uninstall the plugin?

**Comment by GabrielSerealia** [comment]
Never mind I found the option under list view bulk options. Was reading through the change log and found it.

**Comment by GabrielSerealia** [comment]
Ah, I think i need to recreate all my Wordpress gallery blocks

**Comment by giuliopanda** [comment]
No, my plugin modifies images, it doesn't make duplicates, so if you uninstall it, the plugin doesn't restore to the original situation. 
But you can restore the images as long as the original image is there.

**Comment by GabrielSerealia** [comment]
Thanks for getting back to me I had one last question. Does the plug-in allow direct linking to the original file if it has not been resized but the original has not been deleted?
