### ISSUE TITLE
Metadata is not kept

### ISSUE THREAD

**Issue by CaringDev** [giuliopanda/op-bulk-image-resizer#3]
When uploading to the library, EXIF data (e.g. GPS coordinates) is removed.
When processing manually, the data is kept correctly.

**Comment by giuliopanda** [comment]
Hi, I will be honest, I have never checked the Exif data in the conversions I do with the plugin because I have never used them. 
Now I am trying to understand how Exif data works and why only in one process it is removed. 

Thanks for the report.
